language: bash

services:
  - docker

script:
  - docker build -t sunil6680/testing_with_bucket:2048 .
  - docker login -u {docker_username} -p '${docker_pass}'
  - docker push sunil6680/testing_with_bucket:2048

