language: ruby
env:
  - IMAGE = sunil6680/testing_with_bitbucket:traves
services:
  - docker

before_install:
  - docker build -t ${IMAGE} .
  - docker run -d -p 80:4567 ${image} /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run ${IMAGE} /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test
