language: bash

services:
  - docker

script:
  - docker build -t sunil6680/testing_with_bucket:2048 .
  - echo $DOCKER_PASS | docker login -u$DOCKER_USER --password-stdin
  - docker push sunil6680/testing_with_bucket:2048

