language: ruby
env:
  - IMAGE=sunil6680/testing_with_bitbucket:traves
services:
  - docker

before_install:
  - docker build -t ${IMAGE} .
after_success:
  - docker login -u ${docker_username} -p ${docker_pass}
  - docker push ${IMAGE}
