language: bash

services:
  - docker

script:
  - docker build -t sunil6680/testing_with_bitbucket:2048 .
  - docker login -u sunil6680 -p '#$unil6680'
  - docker push sunil6680/testing_with_bitbucket:2048

