language: bash

services:
  - docker

script:
  - docker build -t sunil6680/testing_with_bucket:2048 .
  - echo ${docker_pass} | docker login -u {docker_username} --password-stdin
  - docker push sunil6680/testing_with_bucket:2048

