apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: music-app
  template:
    metadata:
      labels:
        app: music-app
    spec:
      containers:
      - name: music-player
        image: sunil6680/testing_with_bitbucket:3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: impulse-app-svc
spec:
  selector:
    app: music-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer    
   

